packages:
  - extension
catalog:
  "@antfu/eslint-config": ^2.27.3
  "@antfu/ni": ^0.23.0
  "@types/eslint": ^9.6.1
  "@types/node": ^22.5.1
  "@types/vscode": ^1.92.0
  eslint: ^9.9.1
  eslint-factory: ^0.0.2
  ofetch: ^1.3.4
  reactive-vscode: ^0.2.2
  tsup: ^8.2.4
  typescript: ^5.5.4
