// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "cnjimbo"
export const name = "vscode-project-config-updater"
export const version = "0.0.1"
export const displayName = "vscode project config updater"
export const description = undefined
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = 
  | "vscode-project-config-updater.helloWorld"

/**
 * Commands map registed by `cnjimbo.vscode-project-config-updater`
 */
export const commands = {
  /**
   * Hello World
   * @value `vscode-project-config-updater.helloWorld`
   */
  helloWorld: "vscode-project-config-updater.helloWorld",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = 
  | "vscode-project-config-updater.message"

export interface ConfigKeyTypeMap {
  "vscode-project-config-updater.message": string,
}

export interface ConfigShorthandMap {
  message: "vscode-project-config-updater.message",
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registed by `cnjimbo.vscode-project-config-updater`
 */
export const configs = {
  /**
   * The message to show in the notification
   * @key `vscode-project-config-updater.message`
   * @default `"Hello World"`
   * @type `string`
   */
  message: {
    key: "vscode-project-config-updater.message",
    default: "Hello World",
  } as ConfigItem<"vscode-project-config-updater.message">,
}

export interface ScopedConfigKeyTypeMap {
  "message": string,
}

export const scopedConfigs = {
  scope: "vscode-project-config-updater",
  defaults: {
    "message": "Hello World",
  } satisfies ScopedConfigKeyTypeMap,
}

